version: "3"
services:
  mysql-parking:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=parking-db
    ports:
      - "3309:3306"
  rabbitmq-parking-app:
    image: rabbitmq
    ports:
      - "15673:15672"
      - "5673:5672"
  payment-service:
    build: ../payment-service
    ports:
      - "8089:8080"
  parking-service: # doesnt work
    build: ../parking-service
    ports:
      - "8088:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysql-parking:3306/parking-db
      - spring.rabbitmq.host=rabbitmq-parking-app
    depends_on:
      - mysql-parking
      - rabbitmq-parking-app
  psu-adapter:
    build: ../psu-adapter
    depends_on:
      - parking-service
  mail-service:
    image: jakubzzak/mail-service-rabbitmq-python:0.0.2
    environment:
      - APP_NAME=The Parking App
      - MQ_URL=amqp://rabbitmq-parking-app:5673
      - MQ_QUEUE_NAME=mail-queue
      - MQ_CONSUMER_TAG=mail-service-consumer
      - MAIL_SERVER=smtp.websupport.sk
      - MAIL_PORT=465
      - MAIL_USER=
      - MAIL_PASS=
      - MAIL_DEFAULT_SENDER=
    ports:
      - "5001:5001"
    depends_on:
      - rabbitmq-parking-app
