version: "3"
services:
  mysql-parking:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=parking-db
    ports:
      - "3309:3306"
  redis-global-cache:
    image: redis:latest
    ports:
      - "6379:6379"
  rabbitmq-parking-app:
    image: rabbitmq:3-management
    ports:
      - "15673:15672"
      - "5673:5672"
  payment-service:
    image: patrykiciak/payment-service:0.0.2
    ports:
      - "8089:8080"
  parking-service:
    image: patrykiciak/parking-service:latest
    restart: on-failure
    environment:
      - spring.datasource.url=jdbc:mysql://mysql-parking:3306/parking-db
      - spring.rabbitmq.host=rabbitmq-parking-app
      - spring.rabbitmq.port=5672
    ports:
      - "8088:8080"
    depends_on:
      - mysql-parking
      - rabbitmq-parking-app
  psu-adapter:
    image: patrykiciak/psu-adapter:latest
    restart: on-failure
    environment:
      - spring.rabbitmq.host=rabbitmq-parking-app
      - spring.rabbitmq.port=5672
    depends_on:
      - parking-service
  mail-service:
    image: jakubzzak/mail-service-rabbitmq-python:0.0.2
    restart: on-failure
    environment:
      - APP_NAME=The Parking App
      - MQ_URL=amqp://rabbitmq-parking-app:5672
      - MQ_QUEUE_NAME=mail-queue
      - MQ_CONSUMER_TAG=mail-service-consumer
      - MAIL_SERVER=
      - MAIL_PORT=
      - MAIL_USER=
      - MAIL_PASS=
      - MAIL_DEFAULT_SENDER=
    ports:
      - "5001:5001"
    depends_on:
      - rabbitmq-parking-app
  ads-service:
    image: jakubzzak/ads-service-rabbitmq-node:0.0.3
    restart: on-failure
    environment:
      - REQUEST_TIMEOUT_MS=5000
      - FETCH_CYCLE_MS=120000
      - REDIS_URL=redis://redis-global-cache:6379
      - REDIS_DATA_STORAGE=ads
      - REDIS_DATA_EXPIRATION=86400
      - MQ_URL_PARAMS=amqp://rabbitmq-parking-app:5672
      - MQ_QUEUE_NAME=ads-queue
      - MQ_CONSUMER_TAG=ads-service-consumer
    ports:
      - "3003:3000"
    depends_on:
      - redis-global-cache
